### ISSUE TITLE
"% .3g" failure: " 1000" instead of " 1e+03"

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/printf#184]
```
fmt = "%+.4g" value = -9999.833007812500000000
libc:     "-1e+04"
our lib:  "-10000"

fmt = "% .3g" value = 999.779602050781250000
libc:     " 1e+03"
our lib:  " 1000"
```

**Comment by ritesh006** [comment]
Could you please help me to reproduce the same issue

**Comment by eyalroz** [comment]
@ritesh006 : First, thak you for taking an interest in the outstanding issues with this library.

To your point: Just run this program:
```
#include "printf.h"

int main() {
    printf_("ours:  % 01.1g\n", 9.8);
    return 0;
}
```
compiled with the library, of course.

**Comment by ritesh006** [comment]
```
#include <stdio.h>
#include "printf.h"

void _putchar(char c) {
    putchar(c);   //
}

int main(void) {
    printf_("ours:  % 01.1g\n", 9.8);
    return 0;
}
```

```
ours:   10
````

is this the correct approach

**Comment by eyalroz** [comment]
That program gets you the incorrect output that the library produces, yes.

**Comment by ritesh006** [comment]
what actually expected?

**Comment by eyalroz** [comment]
> what actually expected?

We should print: `1e+01`.

**Comment by ls83tda** [comment]
Isn't this the same issue as #156 which was fixed in commit 294e25d? It differs just in whether the "#" is present, to print the decimal point. Both are working correctly in V6.3.0.

**Comment by eyalroz** [comment]
Hmm... you may be right. This is odd... I could have sworn this was still broken. (shakes head) oh well...
